package com.smokelabs.atc.util;

public enum ErrorCode {
    SERVICE_NOT_FOUND,
    ERROR_OCCURRED_DURING_REQUEST_HANDLING,
    SERVICE_IDENTITY_HEADER_MISSING,
    REQUESTING_SERVICE_HAS_INVALID_SCOPE,
    DESTINATION_SERVICE_NOT_FOUND
}
