configurationVersion: "1.0.0"

services:
  auth:
    description: "Authentication and Authorization of users"
    address: "auth.api.smokelabs.com"
    address_postfix: "/v1"
    maintainer: "hlafaille"
    scopes:
      /beginSession:
        methods:
          - POST
        description: "Begins a session"

