configuration_version: "1.0.0"

server:
  responses:
    json:
      enable: true
  request_forking:
    enable: true

services:
  weather:
    description: "Authentication and Authorization of users"
    address: "api.weather.gov"
    maintainer: "US Government"
    scopes:
      /:
        methods:
          - GET
        description: "Health check"

