configurationVersion: "1.0.0"

server:
  responses:
    json:
      enable: true
  request_forking:
    enable: true

services:
  auth:
    description: "Authentication and Authorization of users"
    address: "auth.api.smokelabs.com"
    address_postfix: "/v1"
    maintainer: "hlafaille"
    scopes:
      /beginSession:
        methods:
          - POST
        description: "Begins a session"

