services:
  weather:
    description: Weather
    maintainer: US Government
    hosts:
      - api.weather.gov
    scopes:
      /:
        methods:
          - GET
        description: Health check

  google:
    description: A search engine
    maintainer: Alphabet
    hosts:
      - google.com
    scopes:
      /:
        methods:
          - GET
        description: Health check
    consumes:
      weather:
        /:
          
