name: Checkout & Setup Java/Gradle

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      gradle-version:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'corretto'
    - name: Cache Gradle files
      uses: actions/cache@v4.0.2
      with:
        path: |
          .gradle/caches
          .gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.1.0
