package io.kerosenelabs.atc.util;

public enum ErrorCode {
    SERVICE_NOT_FOUND,
    ERROR_OCCURRED_DURING_REQUEST_HANDLING,
    SERVICE_IDENTITY_HEADER_MISSING,
    CONSUMING_SERVICE_HAS_INVALID_SCOPE,
    PROVIDING_SERVICE_NOT_FOUND,
    REQUEST_SERVICE_NOT_FOUND,
    PROVIDING_SERVICE_HAS_INVALID_SCOPE
}
