name: Gradle (Push)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      
      - name: Cache Gradle files
        uses: actions/cache@v4.0.2
        with:
          path: |
            build/
            gradle/
          key: ${{ runner.os }}-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle
        run: ./gradlew build --scan

      - uses: actions/upload-artifact@v4.3.3
        with:
          name: jar
          path: build/libs/atc-all.jar
