name: OCI

on:
  workflow_run: 
    workflows: ["Gradle"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-base
      